### ISSUE TITLE
Error while upload file with editor

### ISSUE THREAD

**Issue by Trysystems** [FlusherDock1/EditorJS#1]
While uploading file with url /editorjs/plugins/image/uploadFile I got error 
Class 'ReaZzon\Editor\Classes\Plugins\Image\Plugin' not found
/var/www/test/plugins/reazzon/editor/routes.php line 12

Last October CMS, Linux server

**Comment by FlusherDock1** [comment]
Hello do you installed EditorJS or updated it from first versions? Try reinstalling it

**Comment by Trysystems** [comment]
It was fresh installed from marketplace, in two different sites.

**Comment by Trysystems** [comment]
I found the problem. Foleders inside classes/plugins should be lowercase for correct working.

**Comment by FlusherDock1** [comment]
Thanks, will fix in next update.

**Comment by Trysystems** [comment]
Спасибо. Плагин великолепный!

**Comment by FlusherDock1** [comment]
Fixed in 1.4.0
