### ISSUE TITLE
Snippets integration into blocks bar

### ISSUE THREAD

**Issue by impactfactory** [FlusherDock1/EditorJS#11]
**Is your feature request related to a problem? Please describe.**
Usually the clients wishes carousels, cards, accordions as content, inbetween text blocks.

**Describe the solution you'd like**
When creating a new plugin with a component, I can register it as snippet. In the standard editor through clicking a drop down button a list of available snippet appear. a selected snippet appears with a popup for configs or filters etc.

**Describe alternatives you've considered**
I cannot understand out of the documentation how it should be done otherwise...  a bit too complicated for my level unfortunately, I would need a step by step tutorial. :(

**Comment by FlusherDock1** [comment]
Thanks for the feature request! That's really not a big deal, maybe i'll come back with this feature soon.
