### ISSUE TITLE
Undefined index: editor

### ISSUE THREAD

**Issue by sergeitoroptsev** [FlusherDock1/EditorJS#14]
Error

`"Undefined index: editor" on line 71 of ...\plugins\reazzon\editor\classes\event\ExtendRainLabStaticPages.php`

**To Reproduce**
Create new page or update it in Static pages with translations.

**Comment by FlusherDock1** [comment]
Added possible fix in 1.7.5. 

Tested on October V2 2.0.12 and StaticPages 1.4.3

**Comment by FlusherDock1** [comment]
Fixed #[5852aec](https://github.com/FlusherDock1/EditorJS/commit/5852aecd5b31ae8639b72d860735fee4935b7a95)
