### ISSUE TITLE
Better explaining of these two options

### ISSUE THREAD

**Issue by HitArrowLegend** [FlusherDock1/EditorJS#16]
Hello, 

I was wondering if you could further expand what the two options do in the Main panel of EditorJS's settings. 
I'm not quite sure to understand what "Turn off blocking of external requests to EditorJS plugins" and "Disable admin authorization check when querying EditorJS plugins" do.

Thanks

**Comment by LeMaX10** [comment]
Good day!

These parameters mean a security check for access to public REST EditorJS utilities (Uploading images, uploading files, attaching links).

"Turn off blocking of external requests to EditorJS plugins" - The setting is necessary to deny access to methods based on a referrer request, that is, requests that do not come from your site, but from somewhere else. Enabled by default. 

"Disable admin authorization check when querying EditorJS plugins" - This setting forces public methods to check that the request is coming from the browser. In this case, the user's session is also checked, it must contain data on the administrator's authorization. Simply put, this setting checks that whoever makes a request to the methods is an authorized administrator on the site. Enabled by default.

If you turn off any of the settings, the plugin will stop using these security policies. However, if such a need is present, I highly do not recommend - "Disable admin authorization check when querying EditorJS plugins". Ince disabling it will make the site vulnerable to uncontrolled requests to methods, thereby providing a hole for attackers.

**Comment by HitArrowLegend** [comment]
Thank you very much
