### ISSUE TITLE
Blog and translate bug

### ISSUE THREAD

**Issue by sergeitoroptsev** [FlusherDock1/EditorJS#20]
**Describe the bug**
Content dispays as json in translated blog page.

**To Reproduce**
1. Translate blog post content (post.content_html field)
2. Go to frontend to translated blog post

**Comment by vshepel** [comment]
I have some problem on last oc version (2.1.27)

**Comment by FlusherDock1** [comment]
Fixed #[5852aec](https://github.com/FlusherDock1/EditorJS/commit/5852aecd5b31ae8639b72d860735fee4935b7a95)
