### ISSUE TITLE
Doesn't work with latest version of October 2

### ISSUE THREAD

**Issue by PubliAlex** [FlusherDock1/EditorJS#21]
**Describe the bug**
When I add a field of type: editorjs in a model fields.yaml, I get a big textarea with no editorjs in it. Each time I click in this textarea, I get javascript error 

![image](https://user-images.githubusercontent.com/55833027/153431074-4ea90785-8391-4b57-9767-bc39201ffa3f.png)

**To Reproduce**
1. Install latest october 2.x instance
2. Create a model
3. Put a field of type editorjs in your model
4. Try to create a new entry

**Expected behavior**
By reading the doc, an editorjs instance should appear instead of the textarea

**Screenshots**
![image](https://user-images.githubusercontent.com/55833027/153431437-547ef033-194a-4b06-8237-4599dd3d1c20.png)

![image](https://user-images.githubusercontent.com/55833027/153431527-efece61c-090b-418d-9989-e59e9f833a24.png)

Best regards,

**Comment by PubliAlex** [comment]
Edit to bring new informations. I tested the integration with rainlab.blog, it works, so the problem is related to custom models that implement field of editorjs type

**Comment by PubliAlex** [comment]
Another edit, I discovered that it doesn't work when I have a richeditor widget on the same page. If I convert the "teaser" field to a simple textarea, it works.

**Comment by FlusherDock1** [comment]
Thanks for the report!

**Comment by FlusherDock1** [comment]
Checked on latest v2, no problems occured, can you update it to 1.8.0 and test again please?
