### ISSUE TITLE
Not showing in RainLab.Blog post

### ISSUE THREAD

**Issue by adamo** [FlusherDock1/EditorJS#26]
In my new installations of octobercms the editor windows isn't showing in the rainlab blog plugin.

1. I've installed the editor plugin.
2. installed the rainlab blog plugin. 
3. turned on the editor for blog

After the editor didn't show up. 
1. I removed the blog post
2. disabled the editor integration for rainlab blog 
3. proceed to add a new post (without editor)
4. enabled the integration 
5. wen to creating a new blog post but still the normal blog post window appeared

The console doesn't show any errors or warnings. 

The OCMS v is  2.2.15
editor.js plugin version 1.9.2
Other plugins are:

SEO Storm | Total SEO page control in October | 4.3.0 | 4.3.0
-- | -- | -- | --
Magic Forms | Create easy AJAX forms | 1.5.1 | 1.5.1
Blog | Solidna platforma blogera | 1.5.4 | 1.5.4
Strony | Strony statyczne oraz menu. | 1.4.13 | 1.4.13
Editor | Next generation block styled editor | 1.9.2 | 1.9.2
ScaffoldTranslation | Overrides default OctoberCMS scaffold commands to generate translation aware source files | 2.0.0 | 2.0.0
Gallery | Simple admin UI for managing and sorting galleries

I've encountered this problem on previous OCMS and Editor.js versions as well.

**Comment by FlusherDock1** [comment]
Fixed in https://github.com/FlusherDock1/EditorJS/releases/tag/1.9.3

**Comment by adamo** [comment]
Works - thank you
