### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by chrisvidal** [FlusherDock1/EditorJS#27]
How do you make a floating image near a paragraph?

How do you insert an image in a cell inside a table?

I couldn't figure out. Thanks

**Comment by FlusherDock1** [comment]
> How do you make a floating image near a paragraph?

You can't. Because paragraph and image is a different blocks. And there is no nesting inside Editor.js yet.

> How do you insert an image in a cell inside a table?

You can't. There is no nesting inside Editor.js yet.
