### ISSUE TITLE
October CMS v3 FileUpload Bug

### ISSUE THREAD

**Issue by waynelogic** [FlusherDock1/EditorJS#29]
При загрузке файла через EditorJS выходит ошибка `Class "Illuminate\Http\Resources\Json\Resource" not found" on line 11 of C:\Laragon\www\october\plugins\reazzon\editor\classes\plugins\attaches\resources\AttachResource.php`

Судя по всему с 7 версии laravel библиотека `Illuminate\Http\Resources\Json\Resource` переименовалась в `Illuminate\Http\Resources\Json\JsonResource`.
[Источник](https://laracasts.com/discuss/channels/laravel/laravel-7-class-illuminatehttpresourcesjsonresource-not-found).

**Comment by FlusherDock1** [comment]
Thanks for notice! Fixed in [dc48fdc](https://github.com/FlusherDock1/EditorJS/commit/dc48fdc858e95101b07384e9d4d067f5c3c56ce2)
