### ISSUE TITLE
Attach files and images doesn't works due to incompatibility with Laravel 6

### ISSUE THREAD

**Issue by faselunare** [FlusherDock1/EditorJS#30]
**Describe the bug**
Upload and attach images and files doesn't works (error 500)
if the plugin is installed in WinterCMS 1.2

**To Reproduce**
1. Try to attach an image or a file
2. In the browser Console you get ERROR 500

**Screenshots**
![error500](https://user-images.githubusercontent.com/39338657/179236880-26b72c3f-4927-4d89-94e9-64c3d5dd9458.png)

** Solution **
In file 
plugins/reazzon/editor/classes/plugins/attaches/resource/AttachResource.php
change

this
use Illuminate\Http\Resources\Json\Resource;
to
use Illuminate\Http\Resources\Json\JsonResource;

and 
this
class AttachResource extends Resource
to this
class AttachResource extends JsonResource

and

In file 
plugins/reazzon/editor/classes/plugins/image/resource/ImageResource.php
change

this
use Illuminate\Http\Resources\Json\Resource;
to
use Illuminate\Http\Resources\Json\JsonResource;

and 
this
class ImageResource extends Resource
to this
class ImageResource extends JsonResource

**Comment by FlusherDock1** [comment]
Thanks for notice! Fixed in [dc48fdc](https://github.com/FlusherDock1/EditorJS/commit/dc48fdc858e95101b07384e9d4d067f5c3c56ce2)
