### ISSUE TITLE
October media manager/finder

### ISSUE THREAD

**Issue by jlongo** [FlusherDock1/EditorJS#6]
Hi

Is planned to have october ~~file manager~~ media manager/finder integrated ?

TIA

JL

**Comment by FlusherDock1** [comment]
Hi you mean mediafinder?

**Comment by jlongo** [comment]
Hi @FlusherDock1 

Yes, my mistake :)

Regards

JL

**Comment by FlusherDock1** [comment]
Yes it's planned. @yurasovm already built block with media manager support

**Comment by jlongo** [comment]
Thank you! When it will be released ?
TIA
JL
