### ISSUE TITLE
Better Rainlab Blogs integration explanation

### ISSUE THREAD

**Issue by Donokami** [FlusherDock1/EditorJS#8]
**Is your feature request related to a problem? Please describe.**
Hi, I don't really understand how to implement EditorJS with Rainlab blog. Where does the Class extends block should be set?

**Describe the solution you'd like**
Maybe explain more this integration in the documentation!

**Comment by FlusherDock1** [comment]
Hello @Donokami! You can enable integration via simple click in settings of editor.
