### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Trying to access array offset on value of type null").

### ISSUE THREAD

**Issue by Donokami** [FlusherDock1/EditorJS#9]
**Describe the bug**
When setting `{{ post.content_html|raw }}` on my page, I've got this error message: 
`An exception has been thrown during the rendering of a template ("Trying to access array offset on value of type null").`

**Expected behavior**
It should convert json to html on the article page

**Screenshots**
![image](https://user-images.githubusercontent.com/5563277/101247802-bbd6e700-371b-11eb-92fd-4e00a1f7306b.png)

**Additional context**
I installed EditorJS and the driver, and enabled rainlab blogs integration.
This issue seems to be linked to the fact that I'm using PHP 7.4; some code is probably not updated for it

**EDIT: The issue seems to be fixed by PR #7 but not updated on OctoberCMS updating service. Maybe a new release is needed?**

**Comment by FlusherDock1** [comment]
@Donokami Hi! Sorry for long answer. Yes, your problem was fixed in #7 PR, i will push the update to the marketplace soon.
